version: "3"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
# Synology config
#      - PUID=1036
#      - PGID=100
      - TZ=America/New_York
      - UMASK_SET=022 #optional
      - PLEX_CLAIM=${PLEX_CLAIM}
      - VERSION=latest
    volumes:
      - ./config:/config
      bind:
        create_host_path: true
      - /nfs/plex_share:/data/media
    devices:
# intel Hardware accelerator
      - /dev/dri:/dev/dri
    restart: unless-stopped
